-- Esquema inicial de Sticky Burgers

CREATE TABLE producto (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo        VARCHAR(20)  NOT NULL,
    nombre      VARCHAR(80)  NOT NULL,
    descripcion TEXT,
    precio      INTEGER      NOT NULL,
    disponible  BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE pedido (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero           VARCHAR(10)  NOT NULL UNIQUE,
    fecha            TIMESTAMP    NOT NULL,
    cliente_nombre   VARCHAR(120) NOT NULL,
    cliente_telefono VARCHAR(40)  NOT NULL,
    tipo_entrega     VARCHAR(20)  NOT NULL,
    direccion        VARCHAR(200),
    km               NUMERIC(4,2),
    lluvia           BOOLEAN      NOT NULL DEFAULT FALSE,
    subtotal         INTEGER      NOT NULL,
    costo_envio      INTEGER      NOT NULL,
    total            INTEGER      NOT NULL,
    medio_pago       VARCHAR(20)  NOT NULL,
    nota_general     TEXT,
    estado           VARCHAR(20)  NOT NULL
);

CREATE TABLE item_pedido (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id       BIGINT       NOT NULL REFERENCES pedido (id) ON DELETE CASCADE,
    producto_id     BIGINT       REFERENCES producto (id),
    nombre          VARCHAR(80)  NOT NULL,
    precio_unitario INTEGER      NOT NULL,
    cantidad        INTEGER      NOT NULL,
    medallon_extra  BOOLEAN      NOT NULL DEFAULT FALSE,
    nota            VARCHAR(200),
    tipo_linea      VARCHAR(20)  NOT NULL
);

CREATE INDEX idx_item_pedido_pedido ON item_pedido (pedido_id);
CREATE INDEX idx_pedido_fecha ON pedido (fecha);
CREATE INDEX idx_pedido_estado ON pedido (estado);

CREATE TABLE oferta (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo      VARCHAR(120) NOT NULL,
    descripcion TEXT,
    precio      INTEGER      NOT NULL,
    vigencia    VARCHAR(60),
    activa      BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE usuario (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(60)  NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    rol           VARCHAR(20)  NOT NULL
);
